### ISSUE TITLE
SAML Auth fails to correctly log user in on redirect from IdP

### ISSUE THREAD

**Issue by Macel** [salihkiraz/osticket-auth-saml#10]
Clicking the 'Sign in with google' button correctly redirects me to google for authentication.  After successful authentication, I am redirected back to our osTicket site, but the site does not handle the authentication request and actually log me in.  I am brought back to the home page, not logged in.

SAML configuration for my site:

![image](https://user-images.githubusercontent.com/925950/145053704-96545e73-1f4b-41b7-8cf6-6513f873a4e2.png)

In this case, I am specifically using google as my IdP.  Below is a screenshot of google's SAML configuration for our osTicket instance.

![image](https://user-images.githubusercontent.com/925950/145052897-4bc100c1-c8cc-42db-95d2-dbd94ecba090.png)

**Comment by GardnerPL** [comment]
I've seen it in my struggles with integrating this plugin with ADFS. First of all you have wrong Service Provider Entity's ID and ACS URLs. Service Provider Entity ID should be basic URL to your OSTicket, while ACS should lead to /api/auth/saml path in the same URL. Change that in OSTicket and Google configuration. Now you need to have installed and activated a rewrite engine in your webserver since the plugin doesn't create /api/auth/saml file. Instead it just uses rewrite on that path so it can catch SAML response.

**Comment by thenatlgbt** [comment]
> Now you need to have installed and activated a rewrite engine in your webserver since the plugin doesn't create /api/auth/saml file. Instead it just uses rewrite on that path so it can catch SAML response.

What do I have to do now for this? How do I set this up?

**Comment by salihkiraz** [comment]
Hello, the plugin is based on onelogin saml2. Please check your issue at the address below.

https://github.com/onelogin/php-saml/issues

**Comment by DavisGoglin** [comment]
I was installing this and ran into the same thing. 

If you're on Apache, you have to make sure your web server is configured to use ".htaccess" files in the osticket web directory. The relevant one here is `osticket/api/.htaccess`. 

If you're on nginx, you can use a variation of [this](https://www.nginx.com/resources/wiki/start/topics/recipes/osticket/) configuration. 

Instead of `location ~ ^/api/(?:tickets|tasks).*$ {`, use `location ~ ^/api/(?:tickets|tasks|auth).*$ {` to make sure the `/api/auth` URL is handled by `/api/http.php`.

**Comment by nameisazeem** [comment]
Mr @DavisGoglin can you elaborate on it, please? Where should I replace it.
